export const FETCH_NOW_PLAYING = 'FETCH_NOW_PLAYING';
export const FETCH_NOW_PLAYING_SUCCEED = 'FETCH_NOW_PLAYING_SUCCEED';
export const FETCH_NOW_PLAYING_FAILED = 'FETCH_NOW_PLAYING_FAILED';

export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_SUCCEED = 'FETCH_MOVIE_DETAILS_SUCCEED';
export const FETCH_MOVIE_DETAILS_FAILED = 'FETCH_MOVIE_DETAILS_FAILED';
