export const SHOW_MENU = 'SHOW_MENU';
export const HIDE_MENU = 'HIDE_MENU';

export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_FAIL = 'FETCH_GENRES_FAIL';

export const FETCH_GRID_DATA = 'FETCH_GRID_DATA';
export const FETCH_GRID_DATA_SUCCESS = 'FETCH_GRID_DATA_SUCCESS';
export const FETCH_GRID_DATA_FAIL = 'FETCH_GRID_DATA_FAIL';

export const FETCH_DETAILS_DATA = 'FETCH_DETAILS_DATA';
export const FETCH_DETAILS_DATA_SUCCESS = 'FETCH_DETAILS_DATA_SUCCESS';
export const FETCH_DETAILS_DATA_FAIL = 'FETCH_DETAILS_DATA_FAIL';

export const FETCH_SEARCH_DATA = 'FETCH_SEARCH_DATA';
export const FETCH_SEARCH_DATA_SUCCESS = 'FETCH_SEARCH_DATA_SUCCESS';
export const FETCH_SEARCH_DATA_FAIL = 'FETCH_SEARCH_DATA_FAIL';