export const FETCH_TRENDING = 'FETCH_TRENDING';
export const FETCH_TRENDING_SUCCEED = 'FETCH_TRENDING_SUCCEED';
export const FETCH_TRENDING_FAILED = 'FETCH_TRENDING_FAILED';

export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCEED = 'FETCH_DATA_SUCCEED';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';

export const FETCH_DETAILS = 'FETCH_DETAILS';
export const FETCH_DETAILS_SUCCEED = 'FETCH_DETAILS_SUCCEED';
export const FETCH_DETAILS_FAILED = 'FETCH_DETAILS_FAILED';

export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_SUCCEED = 'FETCH_SEARCH_SUCCEED';
export const FETCH_SEARCH_FAILED = 'FETCH_SEARCH_FAILED';

export const FETCH_DISCOVER = 'FETCH_DISCOVER';
export const FETCH_DISCOVER_SUCCEED = 'FETCH_DISCOVER_SUCCEED';
export const FETCH_DISCOVER_FAILED = 'FETCH_DISCOVER_FAILED';

export const SET_PATH = 'SET_PATH';
export const RESET_PAGE = 'RESET_PAGE';
export const LOAD_TITLE = 'LOAD_TITLE';
export const SHOW_DETAILS = 'SHOW_DETAILS';
export const PAGE_GO_BACK = 'PAGE_GO_BACK';
export const NEXT_PAGE = 'NEXT_PAGE';
